version: 2.1
commands:
  setup_environment:
    description: "Setup the machine environment"
    steps:
      - run:
          name: Setup Machine
          command: |
            sudo apt update
            sudo apt install -y curl
            sudo apt-get update
            sudo apt-get install -y git python-pip mysql-client-core-5.5
            sudo apt-get clean
            sudo apt-get autoclean

jobs:
  test:
    parameters:
      memsql_image:
        type: string
    machine: true
    environment:
      MEMSQL_IMAGE: << parameters.memsql_image >>
      MEMSQL_PORT: 5506
      MEMSQL_USER: root
      MEMSQL_DB: test
      TEST_DRIVER: singlestore_test
      TEST_DSN: singlestore_test
      TEST_SERVER: singlestore.example.com
      TEST_SOCKET:
      TEST_SCHEMA: test
      TEST_UID: root
      TEST_PASSWORD:
      CONTINUOUS_INTEGRATION: true
    steps:
      - setup_environment
      - checkout
      - run:
          name: Setup test cluster
          command: |
            echo $PWD
            ls -la
            ./scripts/ensure-test-memsql-cluster.sh
      - run:
          name: Setup ODBC Driver Manager
          command: |
            mkdir odbc_package
            cd odbc_package
            wget https://downloads.mariadb.com/Connectors/odbc/connector-odbc-3.1.7/mariadb-connector-odbc-3.1.7-ga-debian-x86_64.tar.gz
            tar -xvzf mariadb-connector-odbc-3.1.7-ga-debian-x86_64.tar.gz
            sudo install lib64/libmaodbc.so /usr/lib/
            sudo install -d /usr/lib/mariadb/
            sudo install -d /usr/lib/mariadb/plugin/
            sudo install lib/mariadb/plugin/auth_gssapi_client.so /usr/lib/mariadb/plugin/
            sudo install lib/mariadb/plugin/caching_sha2_password.so /usr/lib/mariadb/plugin/
            sudo install lib/mariadb/plugin/client_ed25519.so /usr/lib/mariadb/plugin/
            sudo install lib/mariadb/plugin/dialog.so /usr/lib/mariadb/plugin/
            sudo install lib/mariadb/plugin/mysql_clear_password.so /usr/lib/mariadb/plugin/
            sudo install lib/mariadb/plugin/sha256_password.so /usr/lib/mariadb/plugin/
            cd ..
      - run:
          name: Run tests
          command: |
            export MEMSQL_HOST=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' memsql-integration)
            chmod 777 .travis/build/
            export PROJ_PATH=`pwd`
            export ENTRYPOINT=$PROJ_PATH/.travis/sql
            mkdir tmp
            .travis/gen-ssl.sh singlestore.example.com tmp
            export SSLCERT=$PROJ_PATH/tmp
            cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_OPENSSL=ON -DWITH_SSL=OPENSSL
            cmake --build . --config RelWithDebInfo
            cd test
            export ODBCINI="$PWD/odbc.ini"
            export ODBCSYSINI=$PWD
            ctest -V

workflows:
  test:
    jobs:
      - test:
#          filters:
#            tags:
#              only: /^v.*/
          matrix:
            parameters:
              memsql_image:
                - memsql/cluster-in-a-box:centos-7.0.15-619d118712-1.9.5-1.5.0
                - memsql/cluster-in-a-box:centos-6.8.15-029542cbf3-1.9.3-1.4.1
                - memsql/cluster-in-a-box:6.7.18-db1caffe94-1.6.1-1.1.1
