version: 2.1
commands:
  setup-environment-linux:
    description: "Setup the machine environment"
    steps:
      - run:
          name: Setup Machine
          command: |
            sudo apt update
            sudo apt install -y curl
            sudo apt-get update
            sudo apt-get install -y git python-pip mysql-client-core-5.5
            sudo apt-get clean
            sudo apt-get autoclean
  setup-environment-macos:
    description: "Setup the machine environment"
    steps:
      - run:
          name: Setup Machine
          command: |
            brew update
            brew install curl
            brew install openssl
            brew install libiodbc
            brew install mysql-client
            brew cleanup

orbs:
  win: circleci/windows@2.2.0

jobs:
  build-windows:
    parameters:
      memsql_image:
        type: string
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: systeminfo
      - run: choco install cmake -y
#      - run: $env:Path+=";$Env:ProgramFiles\CMake\bin"; ./makeall.bat
#      - run:
#          name: Setup test cluster
#          command: |
#            bash scripts/ensure-test-memsql-cluster.sh
      - run:
          name: Run tests
          command: |
            bash .circleci/build-windows.sh

  build-macos:
    parameters:
      memsql_image:
        type: string
    macos:
      xcode: 11.0.0
    environment:
      MEMSQL_IMAGE: << parameters.memsql_image >>
      TEST_DRIVER: singlestore_test
      TEST_DSN: singlestore_test
      TEST_SERVER: singlestore.example.com
      TEST_SCHEMA: test
      TEST_UID: root
      TEST_PORT: 5506
      CONTINUOUS_INTEGRATION: true
    steps:
      - setup-environment-macos
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Setup test cluster
          command: |
            ./scripts/ensure-test-memsql-cluster-macos.sh
      - run:
          name: Create test database
          command: |
            mysql -h 127.0.0.1 -u root -P 5506 -e "create database test;"
      - run:
          name: Run tests
          command: |
            ./.circleci/build-osx.sh
  build-linux:
    parameters:
      memsql_image:
        type: string
    machine: true
    environment:
      MEMSQL_IMAGE: << parameters.memsql_image >>
      TEST_DRIVER: singlestore_test
      TEST_DSN: singlestore_test
      TEST_SERVER: singlestore.example.com
      TEST_SCHEMA: test
      TEST_UID: root
      TEST_PORT: 5506
      CONTINUOUS_INTEGRATION: true
    steps:
      - setup-environment-linux
      - checkout
      - run:
          name: Setup test cluster
          command: |
            ./scripts/ensure-test-memsql-cluster.sh
      - run:
          name: Create test database
          command: |
            mysql -h 127.0.0.1 -u root -P 5506 -e "create database test;"
      - run:
          name: Setup ODBC Driver Manager
          command: |
            sudo apt-get update
            sudo apt-get install unixodbc odbcinst
            sudo apt-get install unixodbc-dev
            sudo apt-get install --allow-unauthenticated -y --force-yes -m unixodbc-dev odbcinst1debian2 libodbc1
      - run:
          name: Run tests
          command: |
            ./.circleci/build-linux.sh

workflows:
  test:
    jobs:
      - build-windows:
          matrix:
            parameters:
              memsql_image:
                - memsql/cluster-in-a-box:centos-7.0.15-619d118712-1.9.5-1.5.0
                - memsql/cluster-in-a-box:centos-6.8.15-029542cbf3-1.9.3-1.4.1
                - memsql/cluster-in-a-box:6.7.18-db1caffe94-1.6.1-1.1.1
#      - build-macos:
#          matrix:
#            parameters:
#              memsql_image:
#                - memsql/cluster-in-a-box:centos-7.0.15-619d118712-1.9.5-1.5.0
#                - memsql/cluster-in-a-box:centos-6.8.15-029542cbf3-1.9.3-1.4.1
#                - memsql/cluster-in-a-box:6.7.18-db1caffe94-1.6.1-1.1.1
#      - build-linux:
#          #          filters:
#          #            tags:
#          #              only: /^v.*/
#          matrix:
#            parameters:
#              memsql_image:
#                - memsql/cluster-in-a-box:centos-7.0.15-619d118712-1.9.5-1.5.0
#                - memsql/cluster-in-a-box:centos-6.8.15-029542cbf3-1.9.3-1.4.1
#                - memsql/cluster-in-a-box:6.7.18-db1caffe94-1.6.1-1.1.1
